# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install tavily.python

from tavily import TavilyClient
from google.colab import userdata

def tavily(query):
    key = userdata.get('TAVILY_KEY')
    client = TavilyClient(api_key=key)
    response = client.search(
        query=query,
        max_results=1,
        include_answer=True
    )
    result = response["results"]
    for i in range(len(result)):
        print(result[i]["content"])
    return result