# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install -U google genai

from google.colab import userdata
from google import genai
from google.genai import types
import json
from browser_t import tavily

api = userdata.get('GEMINI_API')
client = genai.Client(api_key=api)

question = input("enter your question----")
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=f"""you are ai assistant please return answer in json format with schema

{{"use_tool":boolean,
 "tool_name":"calculator or browser",
  "answer":"if you can answer other wise null",
  "query":"if you are using tool such as browser than return one line query to search"
}} question by user <<<{question}>>> """,
    config=types.GenerateContentConfig(
        response_mime_type="application/json",
    )
)
gemini = json.loads(response.text)
if gemini["use_tool"] == True:
    print(f"tool used---{gemini['tool_name']}")
    if gemini["tool_name"] == "browser":
        query = gemini["query"]
        print(query)
        browser_result=tavily(query)
        print(browser_result)
print(gemini["answer"])
print(gemini)
